### ISSUE TITLE
Unable to select auto-completed tags

### ISSUE THREAD

**Issue by seanrwcrawford** [kristofa/bookmarker_for_pinboard#29] opened 2021-01-16 18:14 UTC
Currently if I go to save a page and begin typing in tags, I will get the autocomplete options; however I am unable to use the keyboard to select the one I want, nor am I able to use the pointer to click on the desired one. 

If using the arrow keys to select the tag:
- Able to press down once to select a tag, but a second time causes the second tag to be selected and the autocomplete options to close. Currently only able to select up to the second autocomplete tag selection.

If using the mouse to select the tag:
- It just causes the window to close.

MacOS 11.1 on a 2020 M1 Macbook.

**Comment by kristofa** [comment] 2021-01-22 21:24
Unfortunately I can't reproduce this issue. I'm using the extension on a MacBook Pro (Intel) running macOS 11.1 and I can go through the tag list using the keyboard by using the 'down' and 'up' arrow keys also multiple items down. And I can use the 'right' arrow key to select the tag and add it to the edit box.

Selecting a tag using the mouse pointer indeed doesn't work at this moment and is expected.

It is interesting that the issue occurs on a M1 Macbook although I can't think of why this would make a difference.

If anyone else uses "bookmarker for pinboard" and has the same issue or uses a M1 Macbook it would be great if you could update this thread.

**Comment by carldowthwaite** [comment] 2021-02-15 11:23
Just to add that I'm seeing the second behaviour on an Intel (12 inch 2016) MacBook running MacOS 10.15.7

"If using the mouse to select the tag:

- It just causes the window to close."

Keyboard selection is working fine though. Thanks for an extremely useful extension.

**Comment by kristofa** [comment] 2021-02-20 11:20
Thank you for the feedback @carldowthwaite. Good to hear that you find the extension useful 👍 

Selecting a tag with the mouse is currently indeed not supported. I don't immediately see how it can be done with the`NSControlTextEditingDelegate` solution that I'm using right now. A google search also didn't give me any immediate suggestions. There are probably more advanced auto-complete alternatives available with mouse support but I didn't invest time to find out yet.

Personally I don't mind not having mouse support because I find using the keyboard to be faster once you get used to it.

The issue of autocomplete not working at all for @seanrwcrawford is something I really would like to solve but so far I haven't been able to reproduce it.

**Comment by kristofa** [comment] 2022-02-13 08:06
@seanrwcrawford I'm not sure if you still need or want to use "bookmarker for pinboard" but about 3 weeks ago I submitted a new version to the App Store built with the latest Xcode which added Apple Silicon support. 

Might be worth trying again to see if it resolves your issue.

**Comment by kristofa** [comment] 2022-07-31 09:05
I'm using bookmarker for pinboard on an M1 Pro now and am unable to reproduce the issue. It's working as expected. Closing until we have other cases or Information to reproduce.

**Closed as not planned by kristofa** 2022-07-31 09:05 UTC
