### ISSUE TITLE
Timeout when creating bookmark

### ISSUE THREAD

**Issue by geekzter** [kristofa/bookmarker_for_pinboard#30] opened 2021-02-07 16:24 UTC
Each time when I create a bookmark, I get the following error:
'When retrieving previously saved bookmark: Got an error when invoking request to api.pinboard.in: The request timed out.'
This is shown before saving a bookmark. When I do try to save, the bookmark is actually being saved in most cases. However the UI doesn't provide any confirmation of that.

**Comment by kristofa** [comment] 2021-02-20 10:45
Thanks for reporting @geekzter. This is a duplicate of #28.

The reason is that the Pinboard API was very slow to respond a few weeks ago. It was also [reported in this tweet](https://twitter.com/Pinboard/status/1355662344039358470).

You get the error message because the Pinboard API didn't respond with success / error after 7 seconds. This 7 second timeout that has been set in the extension to prevent that we end up being stuck and would wait forever. Because we didn't get a success or error response from the Pinboard API within 7 seconds we don't know what actually happened. But it can indeed be the case that the bookmark was successfully saved. I ran into the same issue. Now the API seems to be responsive again.

**Closed as completed** 2021-02-20 10:45 UTC

**Comment by geekzter** [comment] 2021-03-01 06:42
Hi @kristofa, thanks. Yes, Pinboard was really slow to respond a few weeks back.
